import Foundation
import simd

/// On-device writers for the formats a deliverable actually needs.
///
/// These mirror `packages/formats` byte for byte in intent, so a file exported
/// from the phone and one exported from the studio are interchangeable. Where
/// the two could drift, the TypeScript is the reference implementation and has
/// the test suite — this side is kept deliberately simple.
///
/// What is *not* here is RCS. Autodesk's ReCap formats are proprietary with no
/// published specification, and a guessed binary that fails to open in ReCap is
/// worse than an honest absence. `ExportFormat.rcsBridge` explains the E57 route
/// instead.
enum Exporters {

    // MARK: - PLY

    /// Binary little-endian PLY. The universal point-cloud interchange.
    static func writePointCloudPly(
        positions: [SIMD3<Double>],
        colors: [SIMD3<UInt8>]?,
        to url: URL
    ) throws {
        var header = """
        ply
        format binary_little_endian 1.0
        comment generated by PIXMYD
        element vertex \(positions.count)
        property float x
        property float y
        property float z

        """
        if colors != nil {
            header += """
            property uchar red
            property uchar green
            property uchar blue

            """
        }
        header += "end_header\n"

        var data = Data(header.utf8)
        data.reserveCapacity(data.count + positions.count * (colors == nil ? 12 : 15))

        for (index, position) in positions.enumerated() {
            // float32 is safe here only because coordinates are local. Raw
            // survey coordinates would lose a foot of precision — see
            // Coordinates.swift for why the origin is subtracted first.
            for component in [Float(position.x), Float(position.y), Float(position.z)] {
                withUnsafeBytes(of: component.bitPattern.littleEndian) { data.append(contentsOf: $0) }
            }
            if let colors {
                let c = colors[index]
                data.append(contentsOf: [c.x, c.y, c.z])
            }
        }
        try data.write(to: url)
    }

    /// Binary PLY mesh, with a face element.
    static func writeMeshPly(
        positions: [SIMD3<Float>],
        normals: [SIMD3<Float>]?,
        colors: [SIMD3<UInt8>]?,
        indices: [UInt32],
        to url: URL
    ) throws {
        var header = """
        ply
        format binary_little_endian 1.0
        comment generated by PIXMYD
        element vertex \(positions.count)
        property float x
        property float y
        property float z

        """
        if normals != nil {
            header += """
            property float nx
            property float ny
            property float nz

            """
        }
        if colors != nil {
            header += """
            property uchar red
            property uchar green
            property uchar blue

            """
        }
        header += """
        element face \(indices.count / 3)
        property list uchar uint vertex_indices
        end_header

        """

        var data = Data(header.utf8)
        for (index, position) in positions.enumerated() {
            for component in [position.x, position.y, position.z] {
                withUnsafeBytes(of: component.bitPattern.littleEndian) { data.append(contentsOf: $0) }
            }
            if let normals {
                let n = normals[index]
                for component in [n.x, n.y, n.z] {
                    withUnsafeBytes(of: component.bitPattern.littleEndian) { data.append(contentsOf: $0) }
                }
            }
            if let colors {
                let c = colors[index]
                data.append(contentsOf: [c.x, c.y, c.z])
            }
        }
        for triangle in stride(from: 0, to: indices.count, by: 3) {
            data.append(3)
            for offset in 0..<3 {
                withUnsafeBytes(of: indices[triangle + offset].littleEndian) {
                    data.append(contentsOf: $0)
                }
            }
        }
        try data.write(to: url)
    }

    // MARK: - OBJ

    static func writeObj(
        positions: [SIMD3<Float>],
        normals: [SIMD3<Float>]?,
        colors: [SIMD3<UInt8>]?,
        indices: [UInt32],
        to url: URL
    ) throws {
        var text = "# generated by PIXMYD\n"
        text.reserveCapacity(positions.count * 32)
        for (index, p) in positions.enumerated() {
            text += "v \(fmt(p.x)) \(fmt(p.y)) \(fmt(p.z))"
            if let colors {
                let c = colors[index]
                text += " \(fmt(Float(c.x) / 255)) \(fmt(Float(c.y) / 255)) \(fmt(Float(c.z) / 255))"
            }
            text += "\n"
        }
        if let normals {
            for n in normals { text += "vn \(fmt(n.x)) \(fmt(n.y)) \(fmt(n.z))\n" }
        }
        for triangle in stride(from: 0, to: indices.count, by: 3) {
            // OBJ indices are 1-based.
            let a = indices[triangle] + 1
            let b = indices[triangle + 1] + 1
            let c = indices[triangle + 2] + 1
            text += normals == nil ? "f \(a) \(b) \(c)\n" : "f \(a)//\(a) \(b)//\(b) \(c)//\(c)\n"
        }
        try text.write(to: url, atomically: true, encoding: .utf8)
    }

    // MARK: - GLB

    /// glTF 2.0 binary. One file, no sidecars, opens in nearly everything.
    static func writeGlb(
        positions: [SIMD3<Float>],
        normals: [SIMD3<Float>]?,
        colors: [SIMD3<UInt8>]?,
        indices: [UInt32],
        to url: URL
    ) throws {
        var binary = Data()

        func align(_ data: inout Data, to boundary: Int, with byte: UInt8) {
            let remainder = data.count % boundary
            if remainder != 0 { data.append(contentsOf: [UInt8](repeating: byte, count: boundary - remainder)) }
        }

        let positionOffset = binary.count
        for p in positions {
            for component in [p.x, p.y, p.z] {
                withUnsafeBytes(of: component.bitPattern.littleEndian) { binary.append(contentsOf: $0) }
            }
        }
        let positionLength = binary.count - positionOffset
        align(&binary, to: 4, with: 0)

        var normalOffset = 0
        var normalLength = 0
        if let normals {
            normalOffset = binary.count
            for n in normals {
                for component in [n.x, n.y, n.z] {
                    withUnsafeBytes(of: component.bitPattern.littleEndian) { binary.append(contentsOf: $0) }
                }
            }
            normalLength = binary.count - normalOffset
            align(&binary, to: 4, with: 0)
        }

        var colorOffset = 0
        var colorLength = 0
        if let colors {
            colorOffset = binary.count
            for c in colors { binary.append(contentsOf: [c.x, c.y, c.z]) }
            colorLength = binary.count - colorOffset
            align(&binary, to: 4, with: 0)
        }

        let indexOffset = binary.count
        for index in indices {
            withUnsafeBytes(of: index.littleEndian) { binary.append(contentsOf: $0) }
        }
        let indexLength = binary.count - indexOffset
        align(&binary, to: 4, with: 0)

        // glTF requires min and max on POSITION.
        var minimum = SIMD3<Float>(repeating: .greatestFiniteMagnitude)
        var maximum = SIMD3<Float>(repeating: -.greatestFiniteMagnitude)
        for p in positions {
            minimum = simd_min(minimum, p)
            maximum = simd_max(maximum, p)
        }

        var views: [[String: Any]] = [
            ["buffer": 0, "byteOffset": positionOffset, "byteLength": positionLength, "target": 34962]
        ]
        var accessors: [[String: Any]] = [
            [
                "bufferView": 0, "componentType": 5126, "count": positions.count, "type": "VEC3",
                "min": [minimum.x, minimum.y, minimum.z],
                "max": [maximum.x, maximum.y, maximum.z],
            ]
        ]
        var attributes: [String: Any] = ["POSITION": 0]

        if normals != nil {
            views.append(["buffer": 0, "byteOffset": normalOffset, "byteLength": normalLength, "target": 34962])
            accessors.append([
                "bufferView": views.count - 1, "componentType": 5126,
                "count": positions.count, "type": "VEC3",
            ])
            attributes["NORMAL"] = accessors.count - 1
        }

        if colors != nil {
            views.append(["buffer": 0, "byteOffset": colorOffset, "byteLength": colorLength, "target": 34962])
            accessors.append([
                "bufferView": views.count - 1, "componentType": 5121,
                "count": positions.count, "type": "VEC3", "normalized": true,
            ])
            attributes["COLOR_0"] = accessors.count - 1
        }

        views.append(["buffer": 0, "byteOffset": indexOffset, "byteLength": indexLength, "target": 34963])
        accessors.append([
            "bufferView": views.count - 1, "componentType": 5125,
            "count": indices.count, "type": "SCALAR",
        ])

        let json: [String: Any] = [
            "asset": ["version": "2.0", "generator": "PIXMYD"],
            "scene": 0,
            "scenes": [["nodes": [0]]],
            "nodes": [["mesh": 0]],
            "meshes": [[
                "primitives": [[
                    "attributes": attributes,
                    "indices": accessors.count - 1,
                    "mode": 4,
                ]]
            ]],
            "accessors": accessors,
            "bufferViews": views,
            "buffers": [["byteLength": binary.count]],
        ]

        var jsonData = try JSONSerialization.data(withJSONObject: json)
        // The JSON chunk pads with spaces and the binary chunk with zeros —
        // both are required by the spec, and a viewer that validates will
        // reject the file if they are swapped.
        align(&jsonData, to: 4, with: 0x20)

        var out = Data()
        let total = 12 + 8 + jsonData.count + 8 + binary.count
        for value in [UInt32(0x46546C67), UInt32(2), UInt32(total)] {
            withUnsafeBytes(of: value.littleEndian) { out.append(contentsOf: $0) }
        }
        for value in [UInt32(jsonData.count), UInt32(0x4E4F534A)] {
            withUnsafeBytes(of: value.littleEndian) { out.append(contentsOf: $0) }
        }
        out.append(jsonData)
        for value in [UInt32(binary.count), UInt32(0x004E4942)] {
            withUnsafeBytes(of: value.littleEndian) { out.append(contentsOf: $0) }
        }
        out.append(binary)

        try out.write(to: url)
    }

    // MARK: - LAS

    /// LAS 1.4, point format 2 (with colour).
    ///
    /// LAS stores coordinates as int32 with a scale and offset applied by the
    /// reader. That is a feature: at a 1 mm scale it spans +/-2147 km at exactly
    /// millimetre resolution everywhere, unlike float32 whose resolution
    /// collapses to a foot at State Plane northings. It is also the most
    /// reliable route into ReCap, and therefore into RCS.
    static func writeLas(
        positions: [SIMD3<Double>],
        colors: [SIMD3<UInt8>]?,
        origin: SIMD3<Double>,
        to url: URL
    ) throws {
        let scale = 0.001
        let recordLength: UInt16 = colors == nil ? 20 : 26
        let format: UInt8 = colors == nil ? 0 : 2

        var minimum = SIMD3<Double>(repeating: .greatestFiniteMagnitude)
        var maximum = SIMD3<Double>(repeating: -.greatestFiniteMagnitude)
        for p in positions {
            let world = p + origin
            minimum = simd_min(minimum, world)
            maximum = simd_max(maximum, world)
        }
        if positions.isEmpty { minimum = .zero; maximum = .zero }

        var header = Data()
        func append<T>(_ value: T) {
            withUnsafeBytes(of: value) { header.append(contentsOf: $0) }
        }

        header.append(contentsOf: Array("LASF".utf8))
        append(UInt16(0))              // file source id
        append(UInt16(0))              // global encoding
        append(UInt32(0))              // guid 1
        append(UInt16(0)); append(UInt16(0))
        header.append(contentsOf: [UInt8](repeating: 0, count: 8))
        append(UInt8(1)); append(UInt8(4))  // version 1.4

        func padded(_ text: String, _ length: Int) -> [UInt8] {
            var bytes = Array(text.utf8.prefix(length))
            bytes.append(contentsOf: [UInt8](repeating: 0, count: length - bytes.count))
            return bytes
        }
        header.append(contentsOf: padded("PIXMYD", 32))
        header.append(contentsOf: padded("PIXMYD", 32))

        let calendar = Calendar(identifier: .gregorian)
        let day = calendar.ordinality(of: .day, in: .year, for: Date()) ?? 1
        append(UInt16(day))
        append(UInt16(calendar.component(.year, from: Date())))

        append(UInt16(375))            // header size
        append(UInt32(375))            // offset to point data
        append(UInt32(0))              // number of VLRs
        append(format)
        append(recordLength)
        append(UInt32(min(positions.count, Int(UInt32.max))))   // legacy count
        for i in 0..<5 { append(UInt32(i == 0 ? min(positions.count, Int(UInt32.max)) : 0)) }

        for _ in 0..<3 { append(scale) }
        append(origin.x); append(origin.y); append(origin.z)
        // Header order is max then min, per axis — the opposite of every other
        // bounds record.
        append(maximum.x); append(minimum.x)
        append(maximum.y); append(minimum.y)
        append(maximum.z); append(minimum.z)

        append(UInt64(0))              // waveform record
        append(UInt64(0))              // first EVLR
        append(UInt32(0))              // EVLR count
        append(UInt64(positions.count))
        for i in 0..<15 { append(UInt64(i == 0 ? positions.count : 0)) }

        precondition(header.count == 375, "LAS header must be exactly 375 bytes, got \(header.count)")

        var data = header
        data.reserveCapacity(375 + positions.count * Int(recordLength))
        for (index, position) in positions.enumerated() {
            let world = position + origin
            for axis in 0..<3 {
                let raw = Int32(((world[axis] - origin[axis]) / scale).rounded())
                withUnsafeBytes(of: raw.littleEndian) { data.append(contentsOf: $0) }
            }
            withUnsafeBytes(of: UInt16(0).littleEndian) { data.append(contentsOf: $0) }  // intensity
            data.append(0b00001001)   // return 1 of 1
            data.append(0)            // classification
            data.append(0)            // scan angle
            data.append(0)            // user data
            withUnsafeBytes(of: UInt16(0).littleEndian) { data.append(contentsOf: $0) }  // source id
            if let colors {
                let c = colors[index]
                // 257 maps 255 to 65535 exactly; 256 does not.
                for channel in [c.x, c.y, c.z] {
                    withUnsafeBytes(of: (UInt16(channel) &* 257).littleEndian) {
                        data.append(contentsOf: $0)
                    }
                }
            }
        }
        try data.write(to: url)
    }

    private static func fmt(_ value: Float) -> String {
        String(format: "%.6f", value)
    }
}

// MARK: - Format catalogue

enum ExportFormat: String, CaseIterable, Identifiable {
    case glb, obj, ply, e57, las, html, rcs

    var id: String { rawValue }

    var title: String {
        switch self {
        case .glb: "GLB"
        case .obj: "OBJ"
        case .ply: "PLY"
        case .e57: "E57"
        case .las: "LAS"
        case .html: "Web page"
        case .rcs: "RCS / RCP"
        }
    }

    var kind: Kind {
        switch self {
        case .glb, .obj, .html: .mesh
        case .ply: .either
        case .e57, .las, .rcs: .points
        }
    }

    enum Kind { case mesh, points, either }

    var detail: String {
        switch self {
        case .glb: "One file, opens nearly everywhere. Best default for a mesh."
        case .obj: "Ancient and universal. Opens with no plugin on any machine."
        case .ply: "Point cloud or mesh. The interchange format for scan data."
        case .e57: "Survey interchange. Carries the georeference and per-scan poses."
        case .las: "What GIS and Civil 3D expect. Millimetre precision at State Plane magnitudes."
        case .html:
            "The model inside a web page. Send it to anyone — it opens in a "
                + "browser with nothing installed, and on a phone it can be placed in AR."
        case .rcs: "Autodesk ReCap. Proprietary — see below."
        }
    }

    /// RCS is deliberately absent, and this is the honest reason plus the route.
    var isAvailable: Bool { self != .rcs }
}

/// The documented path from an E57 to an RCP/RCS project.
enum RcsBridge {
    static let explanation = """
    RCS and RCP are Autodesk's own formats. They have no published \
    specification and no redistributable library, so PIXMYD does not write \
    them — a guessed file that fails to open in ReCap would be worse than not \
    offering the format at all.

    Export E57 instead and convert it in one step. The E57 carries the \
    georeference, the per-scan poses and the colour, so nothing is lost.
    """

    static let routes: [(name: String, requires: String, steps: [String])] = [
        (
            name: "ReCap desktop",
            requires: "Autodesk ReCap Pro",
            steps: [
                "New Project, then Import Point Cloud.",
                "Select the exported .e57.",
                "Leave Apply Structure on to keep the per-scan poses.",
                "Index, then Launch Project. ReCap writes the .rcp and its .rcs scans.",
            ]
        ),
        (
            name: "ReCap command line",
            requires: "Autodesk ReCap Pro on Windows",
            steps: [
                #"Recap.exe /import "scan.e57" /output "scan.rcp""#,
                "The .rcp is what AutoCAD, Revit and Navisworks attach.",
            ]
        ),
    ]
}
