/**
 * Wavefront OBJ + MTL writer.
 *
 * OBJ is ancient, verbose, and universally readable — which is exactly why it
 * stays in the list. It is the format that opens on the machine in the trailer
 * with no plugin and no version negotiation.
 *
 * Two traps this writer handles because they bite every naive implementation:
 *
 *   - OBJ indices are 1-based, and negative indices mean "relative to the end".
 *   - OBJ has no vertex colour in the base spec. The de-facto extension appends
 *     r g b to the `v` line, which MeshLab, CloudCompare and Blender read and
 *     which strict parsers ignore harmlessly.
 */

import type { Mesh, PointCloud } from '@pixmyd/core/bundle';

export interface ObjWriteOptions {
  /** Written into the MTL reference and the `o` line. */
  name?: string;
  /** Filename to reference in `mtllib`. Omit to skip material output entirely. */
  materialLibrary?: string;
  /** Appends r g b to each `v` line when the mesh has vertex colours. */
  vertexColors?: boolean;
  /** OBJ is Y-up by convention; set when the source is still Z-up. */
  zUpToYUp?: boolean;
  /** Decimal places. Six gives micrometre resolution at a kilometre. */
  precision?: number;
}

export interface ObjResult {
  obj: string;
  mtl?: string;
  /** Suggested filename for the texture referenced by the MTL. */
  textureFilename?: string;
  texture?: Uint8Array;
}

function fmt(v: number, precision: number): string {
  if (!Number.isFinite(v)) return '0';
  // Trim trailing zeros so the file does not triple in size for round numbers.
  const s = v.toFixed(precision);
  return s.includes('.') ? s.replace(/\.?0+$/, '') || '0' : s;
}

export function writeObj(mesh: Mesh, options: ObjWriteOptions = {}): ObjResult {
  const precision = options.precision ?? 6;
  const name = options.name ?? mesh.name ?? 'pixmyd';
  const lines: string[] = [
    '# generated by PIXMYD',
    `# ${mesh.positions.length / 3} vertices, ${mesh.indices.length / 3} triangles`,
  ];

  const useMtl = options.materialLibrary !== undefined;
  if (useMtl) lines.push(`mtllib ${options.materialLibrary}`);
  lines.push(`o ${name}`);

  const vertexCount = mesh.positions.length / 3;
  const emitColors = options.vertexColors !== false && mesh.colors !== undefined;

  for (let i = 0; i < vertexCount; i++) {
    let x = mesh.positions[i * 3];
    let y = mesh.positions[i * 3 + 1];
    let z = mesh.positions[i * 3 + 2];
    if (options.zUpToYUp) {
      const oy = y;
      y = z;
      z = -oy;
    }
    let line = `v ${fmt(x, precision)} ${fmt(y, precision)} ${fmt(z, precision)}`;
    if (emitColors) {
      line +=
        ` ${fmt(mesh.colors![i * 3], 4)}` +
        ` ${fmt(mesh.colors![i * 3 + 1], 4)}` +
        ` ${fmt(mesh.colors![i * 3 + 2], 4)}`;
    }
    lines.push(line);
  }

  if (mesh.uvs) {
    for (let i = 0; i < vertexCount; i++) {
      // OBJ's V axis points up; image space points down.
      lines.push(`vt ${fmt(mesh.uvs[i * 2], precision)} ${fmt(1 - mesh.uvs[i * 2 + 1], precision)}`);
    }
  }

  if (mesh.normals) {
    for (let i = 0; i < vertexCount; i++) {
      let nx = mesh.normals[i * 3];
      let ny = mesh.normals[i * 3 + 1];
      let nz = mesh.normals[i * 3 + 2];
      if (options.zUpToYUp) {
        const oy = ny;
        ny = nz;
        nz = -oy;
      }
      lines.push(`vn ${fmt(nx, precision)} ${fmt(ny, precision)} ${fmt(nz, precision)}`);
    }
  }

  if (useMtl) lines.push(`usemtl ${name}-material`);

  const hasUv = mesh.uvs !== undefined;
  const hasNormal = mesh.normals !== undefined;
  for (let f = 0; f < mesh.indices.length; f += 3) {
    // 1-based indices
    const a = mesh.indices[f] + 1;
    const b = mesh.indices[f + 1] + 1;
    const c = mesh.indices[f + 2] + 1;
    const ref = (i: number): string =>
      hasUv && hasNormal ? `${i}/${i}/${i}` : hasUv ? `${i}/${i}` : hasNormal ? `${i}//${i}` : `${i}`;
    lines.push(`f ${ref(a)} ${ref(b)} ${ref(c)}`);
  }

  const result: ObjResult = { obj: lines.join('\n') + '\n' };

  if (useMtl) {
    const textureFilename = mesh.texture
      ? `${name}${mesh.texture.mimeType === 'image/jpeg' ? '.jpg' : '.png'}`
      : undefined;
    const mtl = [
      '# generated by PIXMYD',
      `newmtl ${name}-material`,
      'Ka 1.000 1.000 1.000',
      'Kd 1.000 1.000 1.000',
      'Ks 0.000 0.000 0.000',
      'd 1.0',
      // Illumination model 2: colour on, ambient on, specular on.
      'illum 2',
      ...(textureFilename ? [`map_Kd ${textureFilename}`] : []),
    ].join('\n') + '\n';
    result.mtl = mtl;
    if (mesh.texture && textureFilename) {
      result.textureFilename = textureFilename;
      result.texture = mesh.texture.data;
    }
  }

  return result;
}

/**
 * Point clouds as OBJ: vertices with no faces.
 *
 * Not a good idea for anything large — an ASCII vertex costs roughly 40 bytes
 * against 15 for binary PLY — but some CAD importers accept only OBJ, so the
 * option exists. Prefer PLY, E57, or LAS.
 */
export function writePointCloudObj(cloud: PointCloud, options: ObjWriteOptions = {}): string {
  const precision = options.precision ?? 6;
  const lines: string[] = ['# generated by PIXMYD', `# ${cloud.count} points`];
  if (cloud.origin) {
    lines.push(`# pixmyd origin ${cloud.origin.join(' ')}`);
  }
  for (let i = 0; i < cloud.count; i++) {
    let x = cloud.positions[i * 3];
    let y = cloud.positions[i * 3 + 1];
    let z = cloud.positions[i * 3 + 2];
    if (options.zUpToYUp) {
      const oy = y;
      y = z;
      z = -oy;
    }
    let line = `v ${fmt(x, precision)} ${fmt(y, precision)} ${fmt(z, precision)}`;
    if (cloud.colors) {
      line +=
        ` ${fmt(cloud.colors[i * 3] / 255, 4)}` +
        ` ${fmt(cloud.colors[i * 3 + 1] / 255, 4)}` +
        ` ${fmt(cloud.colors[i * 3 + 2] / 255, 4)}`;
    }
    lines.push(line);
  }
  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Reading
// ---------------------------------------------------------------------------

/**
 * Minimal OBJ reader — enough to round-trip our own output and to ingest a mesh
 * a user drops in. Triangulates convex polygons with a fan; ignores groups,
 * smoothing, and materials beyond recording which was active.
 */
export function readObj(text: string): Mesh {
  const positions: number[] = [];
  const colors: number[] = [];
  const uvs: number[] = [];
  const normals: number[] = [];
  const indices: number[] = [];
  // OBJ lets a face reference position/uv/normal at different indices. We flatten
  // to one array per unique combination, which is what GPUs need anyway.
  const vertexMap = new Map<string, number>();
  const outPositions: number[] = [];
  const outColors: number[] = [];
  const outUvs: number[] = [];
  const outNormals: number[] = [];
  let sawColor = false;

  // OBJ indices are 1-based; a negative index counts back from the end of the
  // list *as it stands at that point in the file*, so `count` is passed in.
  const resolve = (index: number, count: number): number =>
    index < 0 ? count + index : index - 1;

  for (const raw of text.split('\n')) {
    const line = raw.trim();
    if (line === '' || line.startsWith('#')) continue;
    const parts = line.split(/\s+/);
    switch (parts[0]) {
      case 'v':
        positions.push(Number(parts[1]), Number(parts[2]), Number(parts[3]));
        if (parts.length >= 7) {
          sawColor = true;
          colors.push(Number(parts[4]), Number(parts[5]), Number(parts[6]));
        } else {
          colors.push(1, 1, 1);
        }
        break;
      case 'vt':
        uvs.push(Number(parts[1]), 1 - Number(parts[2]));
        break;
      case 'vn':
        normals.push(Number(parts[1]), Number(parts[2]), Number(parts[3]));
        break;
      case 'f': {
        const corners: number[] = [];
        for (let i = 1; i < parts.length; i++) {
          const token = parts[i];
          let index = vertexMap.get(token);
          if (index === undefined) {
            const [pRaw, tRaw, nRaw] = token.split('/');
            const p = resolve(Number(pRaw), positions.length / 3);
            outPositions.push(positions[p * 3], positions[p * 3 + 1], positions[p * 3 + 2]);
            outColors.push(colors[p * 3], colors[p * 3 + 1], colors[p * 3 + 2]);
            if (tRaw) {
              const t = resolve(Number(tRaw), uvs.length / 2);
              outUvs.push(uvs[t * 2] ?? 0, uvs[t * 2 + 1] ?? 0);
            }
            if (nRaw) {
              const nIdx = resolve(Number(nRaw), normals.length / 3);
              outNormals.push(
                normals[nIdx * 3] ?? 0,
                normals[nIdx * 3 + 1] ?? 0,
                normals[nIdx * 3 + 2] ?? 0,
              );
            }
            index = outPositions.length / 3 - 1;
            vertexMap.set(token, index);
          }
          corners.push(index);
        }
        // Fan-triangulate. Correct for convex faces, which is what OBJ exporters emit.
        for (let i = 1; i + 1 < corners.length; i++) {
          indices.push(corners[0], corners[i], corners[i + 1]);
        }
        break;
      }
      default:
        break;
    }
  }

  const mesh: Mesh = {
    positions: Float32Array.from(outPositions),
    indices: Uint32Array.from(indices),
  };
  if (outNormals.length > 0) mesh.normals = Float32Array.from(outNormals);
  if (outUvs.length > 0) mesh.uvs = Float32Array.from(outUvs);
  if (sawColor) mesh.colors = Float32Array.from(outColors);
  return mesh;
}
